services:
  - type: web
    name: smart-college-chatbot
    env: python
    buildCommand: ./build.sh
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
