services:
  - type: web
    name: smart-college-chatbot
    runtime: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

