services:
  - type: web
    name: smart-college-chatbot
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
